version: "3.9"

services:
  mysql:
    image: mysql:8
    container_name: stockpilot-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: stockpilot
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis
    container_name: stockpilot-redis
    ports:
      - "6379:6379"

  backend:
    build: ./stockpilot
    container_name: stockpilot-backend
    ports:
      - "5000:5000"
    depends_on:
      - mysql
      - redis
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: root
      DB_NAME: stockpilot
      JWT_SECRET: your_secret_here

  frontend:
    build: ./stockpilot/stockpilot-frontend
    container_name: stockpilot-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

volumes:
  mysql_data: